name: the_phantom_fx
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  flutter_datetime_picker: ^1.5.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.17
  fpdart: ^1.1.0
  supabase_flutter: ^2.8.4
  flutter_bloc: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/logo.png
